name = "idkaboutbytes/string"
version = "1.0.3"
description = "Stringutils package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/string"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Bufferencoder = { repo = "idkaboutbytes/bufferencoder", rev = "v1.0.2" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.3" }
